# Generated by Django 4.1 on 2024-09-08 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='musician',
            name='age',
        ),
        migrations.AlterField(
            model_name='musician',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14)]),
        ),
    ]
